name: Ping URLs

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URLs
        run: |
          curl https://pdf-tools-dljh.onrender.com/
          curl https://algotrading-ufvn.onrender.com/
          
